### ISSUE TITLE
Click tracking does not work with custom element?

### ISSUE THREAD

**Issue by jackiems82** [miguelzakharia/aurelia-application-insights#10]
I have a custom element of a simple button and it does not seem to send any custom events to AppInsighst. I only get events coming directly from a html button element (have not tried other elements). Can you confirm that this plugin does not work with custom elements? If so, I feel the click tracking does not provide that much value atm :-(

I'm using your plugin with version 1.2.0 and applicationinsights-js with version 1.0.11

**Comment by mttmccb** [comment]
Looks like you can do this by overriding the filter on clickTracking.

The default options (below) are merged with what you provide

```
const defaultOptions = {
	logging: {
		enabled: true
	},
	logForwarding: {
		enabled: true
	},
	pageTracking: {
		enabled: false,
		getTitle: function (payload) {
			return payload.instruction.config.title;
		}
	},
	clickTracking: {
		enabled: false,
		filter: function (element) {
			return criteria.isElement(element) &&
				(criteria.isAnchor(element) ||
					criteria.isButton(element));
		}
	}
};
```

So add something like this to the clickTracking config or you could look for a certain attribute

```
filter: (element) => {
  return element instanceof HTMLElement &&
  (element.nodeName.toLowerCase() === 'a' ||
  element.nodeName.toLowerCase() === 'button') ||
  element.nodeName.toLowerCase() === 'my-custom-element');
}
```

**Comment by jackiems82** [comment]
Ah, that is nice. I did not see that, but must admit I did not take the time to go through the code.
However every event is only captured as 'click' in AppInsights with the custom dimensions added of course. I don't know if I did not find the correct view or configuration of a graph in the Azure portal, but with that approach I cannot really filter for the custom dimension. Any clue how that can be achieved?

**Comment by mttmccb** [comment]
Not sure, I add the attributes to the element with google analytics and that plugin is very similar, I'm just starting with AppInsights so haven't got to that yet. 

**Edit**: Yes you need something like `data-appinsights-category="category 1" you can see more in the README

**Comment by jackiems82** [comment]
OK thanks anyway. I guess I should open a new issue with that question and close this one.

**Comment by jackiems82** [comment]
@mttmccb Yes I know. What I meant was that in the Azure portal I only see every event as 'click'. Drilling down then at some point reveals the added dimensions, in your case 'category 1'. In the Azure portal I currently don't know how to filter for the custom dimension. Maybe only the separate Application Insights tool can handle that with a custom query.
