### ISSUE TITLE
Problem building with Aurelia CLI

### ISSUE THREAD

**Issue by thejaff2** [miguelzakharia/aurelia-application-insights#6]
Hi

I have installed the plugin via npm and also added the following in aurelia.json: 

```
"deepmerge",
{
            "name": "aurelia-application-insights",
            "path": "../node_modules/aurelia-application-insights/dist/amd",
            "main": "index"
}
```

When building Im gettings this error: 
```
Tracing aurelia-bootstrap/accordion/aubs-accordion...
Tracing aurelia-bootstrap/pagination/aubs-pagination...
Tracing aurelia-bootstrap/tabs/aubs-tab...
Tracing aurelia-bootstrap/tabs/aubs-tabset...
Tracing aurelia-bootstrap/typeahead/aubs-typeahead...
Tracing nprogress/nprogress...
Tracing au-table...
Tracing au-table/au-table-pagination...
Tracing eonasdan-bootstrap-datetimepicker...
Tracing eonasdan-bootstrap-datetimepicker/css/bootstrap-datetimepicker.min...
Tracing aurelia-bootstrap-datetimepicker...
Tracing aurelia-bootstrap-datetimepicker/abp-datetime-picker...
Tracing deepmerge...
Tracing aurelia-application-insights...
File not found or not accessible: C:/VSOnline/BPL/Core/Development/Återrapportering-SPA/BPL.MinSida.SPA/src/applicationinsights-js.js. Requested by C:\VSOnline\BPL\Core\Development\Återrapportering-SPA\BPL
.MinSida.SPA\node_modules\aurelia-application-insights\dist\amd\index.js
{ Error: ENOENT: no such file or directory, open 'C:\VSOnline\BPL\Core\Development\Återrapportering-SPA\BPL.MinSida.SPA\src\applicationinsights-js.js'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.exports.readFileSync (C:\VSOnline\BPL\Core\Development\Återrapportering-SPA\BPL.MinSida.SPA\node_modules\aurelia-cli\lib\file-system.js:74:13)
    at fileRead (C:\VSOnline\BPL\Core\Development\Återrapportering-SPA\BPL.MinSida.SPA\node_modules\aurelia-cli\lib\build\bundled-source.js:101:27)
    at Object.context.fileRead (C:\VSOnline\BPL\Core\Development\Återrapportering-SPA\BPL.MinSida.SPA\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:179:18)
    at Object.context.load
```

**Comment by miguelzakharia** [comment]
Hi @thejaff2,

Sorry, I'm not familiar with Aurelia CLI. I use webpack in my projects. Maybe someone in the Gitter channel for Aurelia or on StackOverflow can help.

**Comment by Zenuka** [comment]
I'm having the same issue, did you resolve this @thejaff2?

**Comment by thejaff2** [comment]
Nope, sorry to say, I haven't got time to pursue it.

**Comment by Zenuka** [comment]
I figured out that you need to include [applicationinsights-js](https://www.npmjs.com/package/applicationinsights-js) in your aurelia.json. This is how my aurelia.json looks like now:
```json
"deepmerge",
"applicationinsights-js",
{
  "name":"aurelia-application-insights",
  "path": "../node_modules/aurelia-application-insights/dist/amd",
  "main": "index"
}
```
It's already installed because `aurelia-application-insights` needs `applicationinsights-js` as a dependency but you need to include it in the aurelia.json.

**Comment by thejaff2** [comment]
With that in aurelia.json, still doesn't work for me:

`Error: An error occurred while trying to read the map file at C:\VSOnline\BPL\Core\Main\BPL.MinSida.SPA\node_modules\applicationinsights-js\JavaScript\JavaScriptSDK.Module\AppInsightsModule.js.map
Error: ENOENT: no such file or directory, open 'C:\VSOnline\BPL\Core\Main\BPL.MinSida.SPA\node_modules\applicationinsights-js\JavaScript\JavaScriptSDK.Module\AppInsightsModule.js.map'
    at readFromFileMap (C:\VSOnline\BPL\Core\Main\BPL.MinSida.SPA\node_modules\aurelia-cli\lib\build\convert-source-map\index.js:32:11)
    at new Converter (C:\VSOnline\BPL\Core\Main\BPL.MinSida.SPA\node_modules\aurelia-cli\lib\build\convert-source-map\index.js:39:32)
    at Object.exports.fromMapFileComment (C:\VSOnline\BPL\Core\Main\BPL.MinSida.SPA\node_modules\aurelia-cli\lib\build\convert-source-map\index.js:112:10)
    at Object.exports.fromMapFileSource (C:\VSOnline\BPL\Core\Main\BPL.MinSida.SPA\node_modules\aurelia-cli\lib\build\convert-source-map\index.js:131:22)
    at acquireSourceMapForDependency (C:\VSOnline\BPL\Core\Main\BPL.MinSida.SPA\node_modules\aurelia-cli\lib\build\bundle.js:175:33)
    at work.then (C:\VSOnline\BPL\Core\Main\BPL.MinSida.SPA\node_modules\aurelia-cli\lib\build\bundle.js:194:23)`

**Comment by Zenuka** [comment]
That's just a warning that there is a reference to a .map file which is not included in the `applicationinsights-js` package.
I've filed an issue here: https://github.com/Microsoft/ApplicationInsights-JS/issues/484
You can ignore this error because everything works without the .map file.

**Comment by thejaff2** [comment]
Ah, I see, thank you. And I just verified that data indeed is pushed to AppInsights.

**Comment by OzgurDogan** [comment]
I'm trying to get it work, it looks like applicationinsights-js is not bundled in my vendor bundle.  Becaus of this is the ApplicationInsightsJs is undefined when it is injected in aurelia-application-insights Init method.

I've added 

"deepmerge",
"applicationinsights-js",
{
  "name":"aurelia-application-insights",
  "path": "../node_modules/aurelia-application-insights/dist/amd",
  "main": "index"
}
into my aurelia.json. Also tried to add applicationinsights-js manually but I've no clue

**Comment by miguelzakharia** [comment]
Are you seeing an error?

**Comment by OzgurDogan** [comment]
Found the problem, it is related to the latest versions of applicationsinsights-js. When I use version 1.0.8 like you did in your project, it works.

**Comment by miguelzakharia** [comment]
I'm glad it's working. Closing this issue for now.

**Comment by JontyMC** [comment]
Working for me too when using version 1.0.8, but not with latest version. Get "AppInsights" is undefined, seems like a problem importing the AppInsights export.

**Comment by reft** [comment]
@miguelzakharia 

I'm getting: 

> configure: TypeError: Cannot read property 'AppInsights' of undefined

for all versions with aurelia cli and typescript.

You say 1.0.8 works? When I run:

> npm view aurelia-application-insights versions

the only versions available is: [ '1.0.0', '1.1.0', '1.2.0' ].........

**Comment by OzgurDogan** [comment]
@reft you need v1.0.8 of applicationinsights-js. That is a dependency of aurelia-application-insights.

**Comment by reft** [comment]
@OzgurDogan Thanks.

@miguelzakharia Do you have any plans on fixing this with latest applicationinsights-js?
